-- BrightBuy | User & Auth | 03 Seed data
-- Prerequisite: city rows exist (Houston = 1, Dallas = 2 in the Inventory seed).
-- NOTE: the hashes below are PLACEHOLDERS. Real logins need bcrypt hashes generated by the app;
-- replace them or register through the API for demo accounts.

INSERT INTO employee (first_name, last_name, email, password_hash, contact_no, role) VALUES
('Nimal',  'Perera',  'admin@brightbuy.com',     '$2b$10$PLACEHOLDER_HASH_ADMIN_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx', '555-0101', 'Admin'),
('Kamal',  'Silva',   'warehouse@brightbuy.com', '$2b$10$PLACEHOLDER_HASH_WAREHOUSE_xxxxxxxxxxxxxxxxxxxxxxxxxx', '555-0102', 'WarehouseStaff'),
('Sunil',  'Fernando','manager@brightbuy.com',   '$2b$10$PLACEHOLDER_HASH_MANAGER_xxxxxxxxxxxxxxxxxxxxxxxxxxx', '555-0103', 'Management');

INSERT INTO customer (first_name, last_name, email, password_hash, phone, address_line, city_id) VALUES
('Abraham', 'Lincon', 'abrahaml@example.com', '$2b$10$PLACEHOLDER_HASH_CUSTOMER1_xxxxxxxxxxxxxxxxxxxxxxxxxx', '555-0199', '123 Texas Ave',  1),
('Sarah',   'Miller', 'sarahm@example.com',   '$2b$10$PLACEHOLDER_HASH_CUSTOMER2_xxxxxxxxxxxxxxxxxxxxxxxxxx', '555-0200', '45 Elm Street',   2),
('David',   'Brown',  'davidb@example.com',   '$2b$10$PLACEHOLDER_HASH_CUSTOMER3_xxxxxxxxxxxxxxxxxxxxxxxxxx', '555-0201', '9 Ranch Road',    3);
