-- BrightBuy | User & Auth | 01 Schema
-- Prerequisite: city table must exist (Inventory/Delivery script).
-- Run BEFORE Checkout scripts (orders references customer) and Management scripts (report_access_log references employee).
USE brightbuy;

-- CUSTOMER
CREATE TABLE customer (
    customer_id   INT AUTO_INCREMENT PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,      -- bcrypt hash generated by the app (SEC-1)
    phone         VARCHAR(20),
    address_line  VARCHAR(255),
    city_id       INT,
    created_at    DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
    CONSTRAINT uq_customer_email UNIQUE (email),
    CONSTRAINT chk_customer_email CHECK (email LIKE '%_@_%.__%'),
    CONSTRAINT fk_customer_city FOREIGN KEY (city_id) REFERENCES city(city_id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

-- EMPLOYEE (warehouse staff, management, admin)
CREATE TABLE employee (
    employee_id   INT AUTO_INCREMENT PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    contact_no    VARCHAR(20),
    role          VARCHAR(30) NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_employee_email UNIQUE (email),
    CONSTRAINT chk_employee_role CHECK (role IN ('WarehouseStaff','Management','Admin'))
) ENGINE=InnoDB;

-- LOGIN ATTEMPTS (SEC-8 rate limiting)
CREATE TABLE login_attempts (
    attempt_id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    email        VARCHAR(150) NOT NULL,
    user_type    VARCHAR(10)  NOT NULL,
    was_success  BOOLEAN NOT NULL,
    attempted_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
    CONSTRAINT chk_attempt_type CHECK (user_type IN ('customer','employee'))
) ENGINE=InnoDB;

-- INDEXES (CON-6)
CREATE INDEX idx_customer_city       ON customer(city_id);
CREATE INDEX idx_employee_role       ON employee(role);
CREATE INDEX idx_attempts_email_time ON login_attempts(email, attempted_at);
