-- =========================================================
-- BrightBuy | User & Auth | 01 Tables
-- Module owner: Atapattu D.M.
-- Tables: customer, employee, login_attempts, password_reset_token
-- Run after Inventory/01 (customer references city) and before Checkout
-- (orders references customer) and Reporting (the access log references employee).
-- Safe to rerun: existing tables are kept.
-- =========================================================
USE brightbuy;

-- Registered customers. Only they can place orders (BR-1).
CREATE TABLE IF NOT EXISTS customer (
    customer_id   INT AUTO_INCREMENT PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,      -- BCrypt hash generated by the app (SEC-1)
    phone         VARCHAR(20),
    address_line  VARCHAR(255),
    city_id       INT,
    created_at    DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
    CONSTRAINT uq_customer_email UNIQUE (email),
    CONSTRAINT chk_customer_email CHECK (email LIKE '%_@_%.__%'),
    CONSTRAINT fk_customer_city FOREIGN KEY (city_id) REFERENCES city(city_id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    INDEX idx_customer_city (city_id)
) ENGINE=InnoDB;

-- Warehouse staff, management and administrators (SEC-5).
CREATE TABLE IF NOT EXISTS employee (
    employee_id   INT AUTO_INCREMENT PRIMARY KEY,
    first_name    VARCHAR(100) NOT NULL,
    last_name     VARCHAR(100) NOT NULL,
    email         VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    contact_no    VARCHAR(20),
    role          VARCHAR(30) NOT NULL,
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_employee_email UNIQUE (email),
    CONSTRAINT chk_employee_role CHECK (role IN ('WarehouseStaff','Management','Admin')),
    INDEX idx_employee_role (role)
) ENGINE=InnoDB;

-- Every sign-in attempt, used for rate limiting (SEC-8).
CREATE TABLE IF NOT EXISTS login_attempts (
    attempt_id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    email        VARCHAR(150) NOT NULL,
    user_type    VARCHAR(10)  NOT NULL,
    was_success  BOOLEAN NOT NULL,
    attempted_at DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
    CONSTRAINT chk_attempt_type CHECK (user_type IN ('customer','employee')),
    INDEX idx_attempts_email_time (email, attempted_at)
) ENGINE=InnoDB;

-- One-time password reset codes (UI-7). Only the SHA-256 hash of a code is
-- kept here; a code expires after 30 minutes and works once. Exactly one of
-- customer_id / employee_id is set, so both keep a real foreign key.
CREATE TABLE IF NOT EXISTS password_reset_token (
    token_id    BIGINT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT NULL,
    employee_id INT NULL,
    token_hash  CHAR(64) NOT NULL,
    created_at  DATETIME NOT NULL DEFAULT (UTC_TIMESTAMP()),
    expires_at  DATETIME NOT NULL,
    used_at     DATETIME NULL,
    CONSTRAINT uq_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_reset_one_account CHECK ((customer_id IS NULL) <> (employee_id IS NULL)),
    -- MySQL does not allow cascading actions on columns used by a CHECK.
    CONSTRAINT fk_reset_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
    CONSTRAINT fk_reset_employee FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    INDEX idx_reset_customer (customer_id, created_at),
    INDEX idx_reset_employee (employee_id, created_at)
) ENGINE=InnoDB;
